name: Node.js CD

on:
  push:
    branches: [ "master" ]
 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: deploy pakai ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PrIVATE_KEYS }}
          port: 22
          script:
            cd ~/apps/cicd-actions
